# Dockerfile.multiply: Dockerfile for multiply.py
# author: mdeshp10

# Use the latest Python image as base image
FROM python:latest

# Copy the multiply python file to current directory
COPY multiply.py .

# Set Volume directory to /db
VOLUME ["/db"]

# Set the entrypoint command to run when the container starts
ENTRYPOINT ["python", "multiply.py"]