# Dockerfile.divide: Dockerfile for divide.py
# author: mdeshp10

# Use the latest Python image as base image
FROM python:latest

# Copy the divide python file to current directory
COPY divide.py .

# Set Volume directory to /db
VOLUME ["/db"]

# Set the entrypoint command to run when the container starts
ENTRYPOINT ["python", "divide.py"]