# Dockerfile.minus: Dockerfile for minus.py
# author: mdeshp10

# Use the latest Python image as base image
FROM python:latest

# Copy the minus python file to current directory
COPY minus.py .

# Set Volume directory to /db
VOLUME ["/db"]

# Set the entrypoint command to run when the container starts
ENTRYPOINT ["python", "minus.py"]