# Dockerfile.dockerfile: Dockerfile for multiply(.py)
# author: manisha-deshpande

# Use the latest Python image as base image
FROM python:latest

# Copy the multiply python file to current directory
COPY multiply /

# Set the entrypoint command to run when the container starts
ENTRYPOINT ["python", "multiply"]