# Dockerfile.minus: Dockerfile for minus(.py)
# author: manisha-deshpande

# Use the latest Python image as base image
FROM python:latest

# Copy the minus python file to current directory
COPY minus /

# Set the entrypoint command to run when the container starts
ENTRYPOINT ["python", "minus"]